---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: immich
spec:
  components:
    - ../../../../components/dragonfly
    - ../../../../components/kanidm-oidc
    - ../../../../components/postgres/cert
  dependsOn:
    - name: cnpg-operator
      namespace: database
    - name: barman-cloud-plugin
      namespace: database
    - name: dragonfly-operator
      namespace: database
    - name: kanidm
      namespace: security
  healthCheckExprs:
    - apiVersion: dragonflydb.io/v1alpha1
      kind: Dragonfly
      failed: status.phase != 'ready'
      current: status.phase == 'ready'
  interval: 1h
  path: "./kubernetes/apps/selfhosted/immich/app"
  postBuild:
    substitute:
      APP: immich
      APP_NAMESPACE: selfhosted
      DATABASE_EXTENSIONS: |
        [
          { name: vector },
          { name: vchord },
          { name: cube },
          { name: earthdistance }
        ]
      OIDC_DISPLAY_NAME: "Immich"
      OIDC_CALLBACK: /auth/login
      OIDC_EXTRA_CALLBACKS: "[\"app.immich:///oauth-callback\", \"https://immich.negative7.com/user-settings\"]"
      OIDC_LEGACY_CRYPTO: "true"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: selfhosted
