---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: outline-garage
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: outline-garage-secret
    creationPolicy: Owner
    template:
      data:
        ACCESS_KEY_ID: "{{ .garage_cnpg_access_key_id }}"
        SECRET_ACCESS_KEY: "{{ .garage_cnpg_secret_access_key }}"
        REGION: us-east-1
  dataFrom:
    - extract:
        key: outline_garage
      rewrite:
        - regexp:
            source: "(.*)"
            target: "garage_$1"
