---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: outline
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: outline-secret
    creationPolicy: Owner
    template:
      data:
        SECRET_KEY: "{{ .outline_secret_key }}"
        UTILS_SECRET: "{{ .outline_utils_secret }}"
  dataFrom:
    - extract:
        key: outline
      rewrite:
        - regexp:
            source: "(.*)"
            target: "outline_$1"
