---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kanidm
spec:
  chartRef:
    kind: OCIRepository
    name: kanidm
  interval: 30m
  values:
    controllers:
      kanidm:
        type: statefulset
        pod:
          annotations:
            reloader.stakater.com/auto: "true"
          securityContext:
            fsGroup: 2000
            fsGroupChangePolicy: OnRootMismatch
            runAsGroup: 2000
            runAsNonRoot: true
            runAsUser: 2000
        replicas: 1
        containers:
          app:
            image:
              repository: docker.io/kanidm/server
              tag: 1.11.0
            env:
              TZ: America/New_York
              KANIDM_ADMIN_BIND_PATH: /var/run/kanidmd.sock
              KANIDM_DOMAIN: idm.negative7.com
              KANIDM_ORIGIN: https://idm.negative7.com
              KANIDM_BINDADDRESS: "[::]:8443"
              KANIDM_DB_PATH: /data/kanidm.db
              KANIDM_TLS_CHAIN: /certs/tls.crt
              KANIDM_TLS_KEY: /certs/tls.key
              KANIDM_MAIL_RELAY: smtp-relay.system.svc.cluster.local:25
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /status
                    port: 8443
                    scheme: HTTPS
                  initialDelaySeconds: 5
                  periodSeconds: 10
                  timeoutSeconds: 5
                  failureThreshold: 3
              readiness: *probes
            resources:
              requests:
                cpu: 10m
                memory: 64Mi
              limits:
                memory: 256Mi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
      provision:
        pod:
          automountServiceAccountToken: true
          securityContext:
            fsGroup: 65532
            fsGroupChangePolicy: OnRootMismatch
            runAsGroup: 65532
            runAsNonRoot: true
            runAsUser: 65532
        serviceAccount:
          identifier: kanidm-provision
        containers:
          app:
            image:
              repository: ghcr.io/m00nwtchr/kanidm-provision
              tag: main@sha256:bc6b74f818661d369c98b9f3414bf31421450e888455405a4a7a112b5d6f2614
            env:
              KANIDM_INSTANCE: https://idm.negative7.com
              KANIDM_NAMESPACE: security
              KANIDM_TOKEN:
                valueFrom:
                  secretKeyRef:
                    name: kanidm-provision-token
                    key: token
            resources:
              requests:
                cpu: 10m
                memory: 32Mi
              limits:
                memory: 100Mi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
    persistence:
      data:
        existingClaim: kanidm
        advancedMounts:
          kanidm:
            app:
              - path: /data
                subPath: data
      certs:
        type: secret
        defaultMode: 0400
        name: idm-negative7-com-tls
        advancedMounts:
          kanidm:
            app:
              - path: /certs
      tmpfs:
        type: emptyDir
        advancedMounts:
          kanidm:
            app:
              - path: /var/run
                subPath: var-run
      icon-cache:
        type: emptyDir
        advancedMounts:
          provision:
            app:
              - path: /data/icons
    serviceAccount:
      kanidm-provision: {}
    rbac:
      roles:
        kanidm-provision-config:
          type: Role
          rules:
            - apiGroups:
                - ""
              resources:
                - configmaps
              verbs:
                - get
                - list
                - watch
        kanidm-provision-secrets:
          type: ClusterRole
          rules:
            - apiGroups:
                - ""
              resources:
                - secrets
              verbs:
                - create
                - patch
      bindings:
        kanidm-provision-config:
          type: RoleBinding
          roleRef:
            identifier: kanidm-provision-config
          subjects:
            - identifier: kanidm-provision
        kanidm-provision-secrets:
          type: ClusterRoleBinding
          roleRef:
            identifier: kanidm-provision-secrets
          subjects:
            - identifier: kanidm-provision
    route:
      app:
        hostnames:
          - idm.negative7.com
        parentRefs:
          - name: envoy-external
            namespace: network
    service:
      app:
        controller: kanidm
        ports:
          http:
            port: 8443
