---
apiVersion: monitoring.giantswarm.io/v1alpha1
kind: Silence
metadata:
  name: gladius-memory-usage
spec:
  matchers:
    - name: alertname
      value: KubeHpaMaxedOut
      isRegex: false
    - name: horizontalpodautoscaler
      value: keda-hpa-.*
      isRegex: true
