---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
components:
  - ../../components/flux-alerts
  - ../../components/kopiur/secret
resources:
  - ./namespace.yaml
  - ./jellyfin/ks.yaml
  - ./jellyplex-watched/ks.yaml
  - ./jellystat/ks.yaml
  - ./maintainerr/ks.yaml
  - ./plex/ks.yaml
  - ./seerr/ks.yaml
