---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
resources:
  - ./jellyfin/ks.yaml
  - ./maintainerr/ks.yaml
  - ./jellyseerr/ks.yaml
  - ./plex/ks.yaml
  - ./tautulli/ks.yaml
components:
  - ../../components/namespace
  - ../../components/flux/alerts
patches:
  - patch: |
      - op: add
        path: /metadata/name
        value: media
    target:
      kind: Namespace
