---
name: node-exporter
working_dir: docker/truenas/node-exporter
---
name: smartctl-exporter
working_dir: docker/truenas/smartctl-exporter
---
name: nut-exporter
working_dir: docker/truenas/nut-exporter
