[env]
JUST_UNSTABLE = "1"
KUBECONFIG = '{{config_root}}/kubeconfig'
MINIJINJA_CONFIG_FILE = "{{config_root}}/.minijinja.toml"
TALOSCONFIG = '{{config_root}}/talosconfig'

[settings]
pipx.uvx = true

[tools]
"aqua:astral-sh/uv" = "latest"
"aqua:google/yamlfmt" = "latest"
"npm:markdownlint-cli2" = "latest"
"pipx:flux-local" = "latest"
"pipx:ansible" = "latest"
"pipx:ansible-core" = "latest"
"pipx:yamllint" = "latest"


actionlint = "1.7.12"
"aqua:siderolabs/talos" = "1.14.0"
kubectl = "1.37.0"
"aqua:helm/helm" = "4.2.4"
"aqua:fluxcd/flux2" = "2.9.5"
"aqua:kubernetes-sigs/kustomize" = "5.8.1"
"aqua:casey/just" = "1.58.0"
"aqua:jqlang/jq" = "1.8.2"
lefthook = "2.1.12"
"aqua:mikefarah/yq" = "4.53.6"
"aqua:helmfile/helmfile" = "1.7.4"
"github:mitsuhiko/minijinja" = "2.24.0"
"1password-cli" = "2.35.0"
"aqua:charmbracelet/gum" = "2.0.0"
node = "26.8.1"
oxfmt = "0.66.0"
shellcheck = "0.11.0"
go = "latest"
"go:code.gitea.io/tea" = "1.3.3"

[hooks]
postinstall = "ansible-galaxy install -r {{config_root}}/ansible/requirements.yaml && lefthook install"
