---
ignore: |
  .ansible/
  .direnv/
  .private/
  .vscode/
  *.sops.*
  .archive/
  ansible/roles/xanmanning.k3s/

extends: default

rules:
  truthy:
    allowed-values: ["true", "false", "on"]

  comments:
    min-spaces-from-content: 1

  new-line-at-end-of-file: disable

  line-length: disable

  braces:
    min-spaces-inside: 0
    max-spaces-inside: 1

  brackets:
    min-spaces-inside: 0
    max-spaces-inside: 0

  indentation: enable