---
<<<<<<< HEAD
apiVersion: external-secrets.io
=======
apiVersion: external-secrets.io/v1
>>>>>>> 53286c8 (fix(eso): Bump v1beta1 to v1)
kind: ExternalSecret
metadata:
  name: github-webhook-token
  namespace: flux-system
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: github-webhook-token-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        token: "{{ .github_webhook_token }}"
  dataFrom:
    - extract:
        key: flux
