---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kopia
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: kopia-secret
    creationPolicy: Owner
  data:
    - secretKey: KOPIA_PASSWORD
      remoteRef:
        key: volsync-template
        property: KOPIA_PASSWORD
