---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: home-assistant
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: home-assistant-secret
    template:
      data:
        HASS_ECOBEE_API_KEY: "{{ .HASS_ECOBEE_API_KEY }}"
        HASS_PROM_TOKEN: "{{ .HASS_PROM_TOKEN }}"
        HASS_ELEVATION: "{{ .HASS_ELEVATION }}"
        HASS_LATITUDE: "{{ .HASS_LATITUDE }}"
        HASS_LONGITUDE: "{{ .HASS_LONGITUDE }}"
        HASS_GITHUB_TOKEN: "{{ .HASS_GITHUB_TOKEN }}"
        HASS_EXTERNAL_URL: "{{ .HASS_EXTERNAL_URL }}"
        HASS_PLEX: "{{ .HASS_PLEX }}"
        HASS_PIRATEAPI: "{{ .HASS_PIRATEAPI }}"
  dataFrom:
    - extract:
        key: home-assistant