---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io
kind: ExternalSecret
metadata:
  name: plex-jellyfin-sync
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: plex-jellyfin-sync-secret
    creationPolicy: Owner
  data:
    - secretKey: PLEX_TOKEN
      remoteRef:
        key: plex
        property: token
    - secretKey: JELLYFIN_API_KEY
      remoteRef:
        key: jellyfin
        property: api_key
