---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: plex-jellyfin-sync
spec:
  chartRef:
    kind: OCIRepository
    name: plex-jellyfin-sync
  interval: 30m
  values:
    controllers:
      jellyfin-sync:
        annotations:
          reloader.stakater.com/auto: "true"
        type: cronjob
        cronjob:
          schedule: 0 * * * *
          backoffLimit: 0
          concurrencyPolicy: Forbid
          successfulJobsHistory: 1
          failedJobsHistory: 1
          ttlSecondsAfterFinished: 3600
        containers:
          app:
            image:
              repository: ghcr.io/luigi311/jellyplex-watched
              tag: 8.3.0@sha256:8baa19c0288b0c53b58b422402f8a61f24eca6a32986ed4519c31035da4c86d9
            envFrom:
              - secretRef:
                  name: jellyfin-sync-secret
            env:
              DEBUG_LEVEL: debug
              DRYRUN: false
              JELLYFIN_BASEURL: http://jellyfin.media.svc.cluster.local:8096
              LOGFILE: /tmp/sync.log
              MARK_FILE: /tmp/mark.log
              PLEX_BASEURL: http://plex.media.svc.cluster.local:32400
              RUN_ONLY_ONCE: true
              TZ: America/New_York
              LIBRARY_MAPPING: '{ "Shows": "TV Shows" }'
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 512Mi
        pod:
          hostUsers: false
          restartPolicy: Never
    persistence:
      tmp:
        type: emptyDir
