---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mainsail
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: mainsail
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
  values:
    controllers:
      mainsail:
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          securityContext:
            runAsUser: 2000
            runAsGroup: 2000
            fsGroup: 2000
            fsGroupChangePolicy: OnRootMismatch
        containers:
          app:
            image:
              repository: ghcr.io/mainsail-crew/mainsail
              # mainsail doesnt tag docker tags
              tag: latest@sha256:079e20b9c7a783c072b2aa50c7033e313aedea71bb5f46f577cef463b5d5e3d2
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
            resources:
              requests:
                cpu: 100m
                memory: 512Mi
              limits:
                memory: 512Mi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 2000
        runAsGroup: 2000
        fsGroup: 2000
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile: {type: RuntimeDefault}

    service:
      app:
        controller: mainsail
        ports:
          http:
            port: 80
    route:
      app:
        hostnames:
          - voron.negative7.com
        parentRefs:
          - name: envoy-internal
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - identifier: app
                port: 80


    persistence:
      config-file:
        type: configMap
        name: mainsail
        globalMounts:
          - path: /usr/share/nginx/html/config.json
            subPath: config.json
            readOnly: true
