---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: esphome
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.6.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    controllers:
      esphome:
        annotations:
          reloader.stakater.com/auto: "true"

        pod:
          hostNetwork: true

        containers:
          app:
            image:
              repository: ghcr.io/esphome/esphome
              tag: 2024.12.4
            probes:
              liveness:
                enabled: false
              readiness:
                enabled: false
              startup:
                enabled: false
            resources:
              requests:
                cpu: 5m
                memory: 137M
              limits:
                memory: 500M
          code-server:
            image:
              repository: ghcr.io/coder/code-server
              tag: 4.96.4@sha256:f93810f7f6636b3af3b1a750faf612349cddb89fbb6d28d69123a214fc75ee9e
            args: [
              "--auth", "none",
              "--user-data-dir", "/config/.vscode",
              "--extensions-dir", "/config/.vscode",
              "--port", "12321",
              "/config"
            ]
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 512Mi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile: { type: RuntimeDefault }

    service:
      app:
        controller: esphome
        ports:
          http:
            port: 6052
          code-server:
            port: 12321

    ingress:
      app:
        className: internal-nginx
        annotations:
          external-dns.alpha.kubernetes.io/target: internal.negative7.com
        hosts:
          - host: &hostName "{{ .Release.Name }}.negative7.com"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *hostName
      code-server:
        enabled: true
        className: internal-nginx
        annotations:
          external-dns.alpha.kubernetes.io/target: internal.negative7.com
        hosts:
          - host: &hostNameCS  'esphome-code.negative7.com'
            paths:
              - path: /
                service:
                  identifier: app
                  port: code-server
        tls:
          - hosts:
              - *hostNameCS

    persistence:
      config:
        existingClaim: esphome
        globalMounts:
          - path: /config
      secrets:
        type: secret
        name: esphome-secrets
        globalMounts:
          - path: /config/secrets.yaml
            subPath: secrets.yaml
      esphome-cache:
        type: emptyDir
        globalMounts:
          - path: /config/.esphome
