---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: actual
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: actual-secret
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: actual
        property: password
    - secretKey: sync_id
      remoteRef:
        key: actual
        property: sync_id
    - secretKey: bearer_token
      remoteRef:
        key: actual
        property: bearer_token
