---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: alloy
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: alloy
  values:
    fullnameOverride: alloy
    alloy:
      configMap:
        create: false
        name: &name alloy-configmap
        key: config.alloy
    controller:
      podAnnotations:
        configmap.reloader.stakater.com/reload: *name
    serviceMonitor:
      enabled: true
