---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
<<<<<<< HEAD
apiVersion: external-secrets.io
=======
apiVersion: external-secrets.io/v1
>>>>>>> 53286c8 (fix(eso): Bump v1beta1 to v1)
kind: ExternalSecret
metadata:
  name: actions-runner-controller
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: actions-runner-controller-secret
    creationPolicy: Owner
  data:
    - secretKey: github_app_id
      remoteRef:
        key: actions-runner-controller
        property: github_app_id
    - secretKey: github_app_installation_id
      remoteRef:
        key: actions-runner-controller
        property: github_app_installation_id
    - secretKey: github_app_private_key
      remoteRef:
        key: actions-runner-controller
        property: github_app_private_key