---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/postgresql.cnpg.io/cluster_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: jellystat-postgresql
spec:
  description: PostgreSQL cluster for Jellystat
  imageName: ghcr.io/cloudnative-pg/postgresql:18.4-standard-trixie
  instances: 2
  storage:
    size: 2Gi
    storageClass: miroir-replicated
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      memory: 512Mi
  postgresql:
    parameters:
      max_connections: "100"
      shared_buffers: 128MB
  nodeMaintenanceWindow:
    inProgress: false
    reusePVC: true
  primaryUpdateStrategy: unsupervised
  monitoring:
    enablePodMonitor: true
  bootstrap:
    initdb:
      database: jellystat
      owner: jellystat
      encoding: UTF8
