---
<<<<<<< HEAD
apiVersion: external-secrets.io
=======
apiVersion: external-secrets.io/v1
>>>>>>> 53286c8 (fix(eso): Bump v1beta1 to v1)
kind: ExternalSecret
metadata:
  name: cloudflared-tunnel
  namespace: networking
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: cloudflared-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        credentials.json: |
          {
            "AccountTag": "{{ index . "account-tag" }}",
            "TunnelSecret": "{{ index . "tunnel-secret" }}",
            "TunnelID": "{{ .tunnel_id }}"
          }
        TunnelID: "{{ .tunnel_id }}"
  dataFrom:
    - extract:
        key: cloudflare
