---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sparkyfitness
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: sparkyfitness-secret
    creationPolicy: Owner
    template:
      data:
        SPARKY_FITNESS_API_ENCRYPTION_KEY: "{{ .sparkyfitness_api_encryption_key }}"
        BETTER_AUTH_SECRET: "{{ .sparkyfitness_better_auth_secret }}"
  dataFrom:
    - extract:
        key: sparkyfitness
      rewrite:
        - regexp:
            source: "(.*)"
            target: "sparkyfitness_$1"
