---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app postgres
  namespace: &namespace database
spec:
  targetNamespace: *namespace
  dependsOn:
    - name: cnpg-operator
      namespace: database
    - name: barman-cloud-plugin
      namespace: database
    - name: cert-manager
      namespace: cert-manager
  healthChecks:
    - apiVersion: postgresql.cnpg.io/v1
      kind: Cluster
      name: postgres
      namespace: database
  path: ./kubernetes/apps/database/postgres/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: true
  interval: 1h
  retryInterval: 1m
  timeout: 10m
