---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: silence-operator
spec:
  interval: 30m
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    alertmanagerAddress: http://alertmanager.monitoring.svc.cluster.local:9093
    image:
      registry: quay.io
      # TODO: Enable on next Flux release and remove name & tag
      # REF: https://github.com/fluxcd/helm-controller/pull/1212
      name: giantswarm/silence-operator
      tag: 0.16.1
    networkPolicy:
      enabled: false