---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: konflate
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: konflate-secret
    creationPolicy: Owner
    template:
      data:
        KONFLATE_WEBHOOK_SECRET: "{{ .webhook_secret }}"
        KONFLATE_APP_PRIVATE_KEY: "{{ .negative7_bot_key }}"
        KONFLATE_APP_CLIENT_ID: "{{ .negative7_bot_client_id }}"
  dataFrom:
    - extract:
        key: konflate
    - extract:
        key: Github
