---
# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/refs/heads/main/schema/compose-spec.json
services:
  garage:
    container_name: garage
    image: docker.io/dxflrs/garage:v2.3.0
    command:
      - /garage
      - "-c"
      - /etc/garage/garage.toml
      - server
    user: "2000:2000"
    restart: unless-stopped
    logging:
      driver: json-file
    network_mode: host
    environment:
      - GARAGE_ADMIN_TOKEN=${GARAGE_ADMIN_TOKEN}
      - GARAGE_RPC_SECRET=${GARAGE_RPC_SECRET}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config/garage.toml:/etc/garage/garage.toml:ro
      - /mnt/tank/apps/garage/meta:/var/lib/garage/meta
      - /mnt/tank/apps/garage/data:/var/lib/garage/data

  garage-webui:
    container_name: garage-webui
    hostname: garage.internal
    image: docker.io/khairul169/garage-webui:1.1.0
    restart: unless-stopped
    logging:
      driver: json-file
    network_mode: host
    environment:
      - PORT=3909
      - API_BASE_URL=http://localhost:9002
      - S3_ENDPOINT_URL=http://localhost:9000
      - S3_REGION=us-east-1
      - API_ADMIN_KEY=${GARAGE_ADMIN_TOKEN}
    volumes:
      - /etc/localtime:/etc/localtime:ro
