---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: seerr
spec:
  interval: 30m
  timeout: 5m
  path: "./kubernetes/apps/media/seerr/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: media
  wait: false
  components:
    - ../../../../components/volsync
    - ../../../../components/keda/nas-nfs-scaler
  postBuild:
    substitute:
      APP: seerr
      VOLSYNC_CAPACITY: 5Gi
