---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
<<<<<<< HEAD
apiVersion: external-secrets.io
=======
apiVersion: external-secrets.io/v1
>>>>>>> 53286c8 (fix(eso): Bump v1beta1 to v1)
kind: ExternalSecret
metadata:
  name: alertmanager-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: alertmanager-secret
    creationPolicy: Owner
  data:
    - secretKey: pushover_api_token
      remoteRef:
        key: pushover
        property: PUSHOVER_TOKEN
    - secretKey: pushover_api_userkey
      remoteRef:
        key: pushover
        property: PUSHOVER_USER_KEY
