---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: downloads
resources:
  # Flux-Kustomizations
  - ./prowlarr/ks.yaml
  - ./radarr/ks.yaml
  - ./recyclarr/ks.yaml
  - ./sabnzbd/ks.yaml
  - ./sonarr/ks.yaml
components:
  - ../../components/namespace
  - ../../components/flux/alerts
  - ../../components/flux/sops
patches:
  - patch: |
      - op: add
        path: /metadata/name
        value: downloads
    target:
      kind: Namespace
