---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ${APP}-db
  namespace: &namespace database
spec:
  dependsOn:
    - name: postgres
      namespace: database
  healthChecks:
    - apiVersion: postgresql.cnpg.io/v1
      kind: Database
      name: postgres-${APP}
      namespace: *namespace
  interval: 1h
  path: ./kubernetes/components/postgres/base/database
  postBuild:
    substitute:
      APP: ${APP}
      OWNER: ${DATABASE_OWNER:=${APP}}
  prune: true
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
