---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: home
resources:
  - ./esphome/ks.yaml
  - ./home-assistant/ks.yaml
  - ./scrypted/ks.yaml
  - ./zigbee2mqtt/ks.yaml
components:
  - ../../components/namespace
  - ../../components/flux/alerts
patches:
  - patch: |
      - op: add
        path: /metadata/name
        value: home
    target:
      kind: Namespace