---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "negative7-com"
  namespace: networking
spec:
  secretName: "negative7-com-tls"
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "negative7.com"
  dnsNames:
    - "negative7.com"
    - "*.negative7.com"
