---
# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/refs/heads/main/schema/compose-spec.json
secrets:
  1pw_token:
    file: /home/nasadmin/.config/doco-cd/1pw_token
  api_secret:
    file: /home/nasadmin/.config/doco-cd/api_secret
  webhook_secret:
    file: /home/nasadmin/.config/doco-cd/webhook_secret
services:
  app:
    container_name: doco-cd
    environment:
      API_SECRET_FILE: /run/secrets/api_secret
      DEPLOY_CONFIG_BASE_DIR: ./docker/lviv/
      HTTP_PORT: 8880
      LOG_LEVEL: info
      POLL_CONFIG: |-
        - url: https://github.com/negative7/home-ops.git
          reference: refs/heads/main
          interval: 3600
      SECRET_PROVIDER: 1password
      SECRET_PROVIDER_ACCESS_TOKEN_FILE: /run/secrets/1pw_token
      TZ: America/New_York
      WEBHOOK_SECRET_FILE: /run/secrets/webhook_secret
    healthcheck:
      test:
        - CMD
        - /doco-cd
        - healthcheck
      start_period: 15s
      interval: 30s
      timeout: 5s
      retries: 3
    image: ghcr.io/kimdre/doco-cd:0.89.1@sha256:1da6393b7517b267c05036c36343dce7e1d2a0382b9acdd042287f332a5111a8
    ports:
      - 8880:8880
    restart: unless-stopped
    secrets:
      - 1pw_token
      - api_secret
      - webhook_secret
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - data:/data
volumes:
  data: {}