---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: forgejo-runner
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: forgejo-runner-secret
    creationPolicy: Owner
  data:
    - secretKey: token
      remoteRef:
        key: forgejo-runner-k8s
        property: token
    - secretKey: uuid
      remoteRef:
        key: forgejo-runner-k8s
        property: uuid
