---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: spegel
spec:
  interval: 30m
  chart:
    spec:
      chart: spegel
      version: v0.0.30
      sourceRef:
        kind: HelmRepository
        name: spegel
        namespace: flux-system
      interval: 30m
  values:
    spegel:
      appendMirrors: true
      containerdSock: /run/containerd/containerd.sock
      containerdRegistryConfigPath: /etc/cri/conf.d/hosts
    service:
      registry:
        hostPort: 29999
    serviceMonitor:
      enabled: true
