---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app immich
spec:
  chartRef:
    kind: OCIRepository
    name: *app
  interval: 1h
  values:
    controllers:
      main:
        containers:
          main:
            image:
              # renovate: datasource=github-releases depName=immich-app/immich
              tag: v3.1.0
            env:
              TZ: America/New_York
              DB_URL:
                valueFrom:
                  secretKeyRef:
                    name: "{{ .Release.Name }}-postgres"
                    key: url
              REDIS_HOSTNAME: immich-dragonfly.selfhosted.svc.cluster.local

    immich:
      metrics:
        enabled: true
      persistence:
        library:
          existingClaim: immich-library

    server:
      controllers:
        main:
          pod:
            securityContext:
              runAsUser: 1000
              runAsGroup: 1000
              runAsNonRoot: true
              fsGroup: 1000
              fsGroupChangePolicy: OnRootMismatch

          containers:
            main:
              resources:
                requests:
                  cpu: 11m
                  memory: 1Gi
                limits:
                  memory: 2560Mi

    machine-learning:
      controllers:
        main:
          strategy: Recreate

          containers:
            main:
              resources:
                requests:
                  cpu: 10m
                  memory: 512Mi
                limits:
                  memory: 2Gi
      persistence:
        cache:
          type: persistentVolumeClaim
          size: 10Gi
          accessMode: ReadWriteOnce
