---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich
spec:
  chartRef:
    kind: OCIRepository
    name: immich
  interval: 30m
  values:
    controllers:
      main:
        containers:
          main:
            env:
              TZ: America/New_York
              DB_URL:
                valueFrom:
                  secretKeyRef:
                    name: immich-postgres
                    key: url
              REDIS_HOSTNAME: immich-dragonfly.selfhosted.svc.cluster.local

    immich:
      metrics:
        enabled: true
      persistence:
        library:
          existingClaim: immich-library

    server:
      controllers:
        main:
          pod:
            securityContext:
              fsGroup: 1000
              fsGroupChangePolicy: OnRootMismatch
          containers:
            main:
              image:
                tag: v3.1.0@sha256:b434cb9287eea1471c9974845914d4dd328c9c2d652e446ed4930f99944f0ceb
              resources:
                requests:
                  cpu: 11m
                  memory: 1Gi
                limits:
                  memory: 2560Mi
      persistence:
        postgres-cert:
          type: secret
          name: postgres-immich-cert
          defaultMode: 0400
          globalMounts:
            - path: /var/run/secrets/postgresql
        postgres-client-ca:
          type: secret
          name: postgres-client-ca
          defaultMode: 0440
          globalMounts:
            - path: /var/run/secrets/postgres-client-ca

    machine-learning:
      controllers:
        main:
          strategy: Recreate
          containers:
            main:
              image:
                tag: v3.1.0@sha256:5a0839dc5303cd7215bcd2180a26aed3af41675aefb3e75e5157e9f10ad16e6e
              resources:
                requests:
                  cpu: 200m
                  memory: 1Gi
                limits:
                  memory: 4Gi
      persistence:
        cache:
          type: persistentVolumeClaim
          size: 10Gi
          accessMode: ReadWriteOnce
