---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: zigbee2mqtt-exporter
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: zigbee2mqtt-exporter-secret
    creationPolicy: Owner
  dataFrom:
    - secretKey: mqtt_user
      remoteRef:
        key: EMQX
        property: user_mqtt_username
    - secretKey: mqtt_password
      remoteRef:
        key: EMQX
        property: user_mqtt_password