---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io
kind: ExternalSecret
metadata:
  name: emqx
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: emqx-secret
    creationPolicy: Owner
    template:
      data:
        EMQX_DASHBOARD__DEFAULT_USERNAME: '{{ index . "username" }}'
        EMQX_DASHBOARD__DEFAULT_PASSWORD: '{{ index . "password" }}'
  dataFrom:
    - extract:
        key: EMQX