---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
<<<<<<< HEAD
apiVersion: external-secrets.io
=======
apiVersion: external-secrets.io/v1
>>>>>>> 53286c8 (fix(eso): Bump v1beta1 to v1)
kind: ExternalSecret
metadata:
  name: prowlarr
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: prowlarr-secret
    creationPolicy: Owner
  data:
    - secretKey: api_key
      remoteRef:
        key: prowlarr
        property: api_key
