---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: homepage
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: homepage-secret
    creationPolicy: Owner
    template:
      data:
        HOMEPAGE_VAR_SONARR_KEY: "{{ .sonarr_api_key }}"
        HOMEPAGE_VAR_RADARR_KEY: "{{ .radarr_api_key }}"
        HOMEPAGE_VAR_PROWLARR_KEY: "{{ .prowlarr_api_key }}"
        HOMEPAGE_VAR_PLEX_TOKEN: "{{ .plex_token }}"
        HOMEPAGE_VAR_JELLYFIN_KEY: "{{ .hp_jellyfin_key }}"
        HOMEPAGE_VAR_SEERR_KEY: "{{ .hp_seer_key }}"
        HOMEPAGE_VAR_HASS_KEY: "{{ .hp_hass_key }}"
        HOMEPAGE_VAR_BAZARR_KEY: "{{ .hp_bazarr_key }}"
        HOMEPAGE_VAR_SABNZBD_KEY: "{{ .hp_sabnzbd_key }}"
        HOMEPAGE_VAR_QBIT_KEY: "{{ .hp_qbit_key }}"
  dataFrom:
    - extract:
        key: sonarr
      rewrite:
        - regexp:
            source: "(.*)"
            target: "sonarr_$1"
    - extract:
        key: radarr
      rewrite:
        - regexp:
            source: "(.*)"
            target: "radarr_$1"
    - extract:
        key: prowlarr
      rewrite:
        - regexp:
            source: "(.*)"
            target: "prowlarr_$1"
    - extract:
        key: plex
      rewrite:
        - regexp:
            source: "(.*)"
            target: "plex_$1"
    - extract:
        key: homepage-secrets
      rewrite:
        - regexp:
            source: "(.*)"
            target: "hp_$1"
