---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sabnzbd
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 4.1.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s-labs
        namespace: flux-system
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
    - name: openebs
      namespace: openebs
  values:
    controllers:
      sabnzbd:
        annotations:
          reloader.stakater.com/auto: "true"

        pod:
          securityContext:
            runAsUser: 2000
            runAsGroup: 2000
            runAsNonRoot: true
            fsGroup: 2000
            fsGroupChangePolicy: OnRootMismatch

        containers:
          app:
            image:
              repository: ghcr.io/home-operations/sabnzbd
              tag: 4.5.1
            env:
              SABNZBD__PORT: &port 8080
              SABNZBD__HOST_WHITELIST_ENTRIES: >-
                sabnzbd,
                sabnzbd.downloads,
                sabnzbd.downloads.svc,
                sabnzbd.downloads.svc.cluster,
                sabnzbd.downloads.svc.cluster.local,
                sabnzbd.negative7.com
              SABNZBD__API_KEY:
                valueFrom:
                  secretKeyRef:
                    name: sabnzbd-secret
                    key: api_key
              SABNZBD__NZB_KEY:
                valueFrom:
                  secretKeyRef:
                    name: sabnzbd-secret
                    key: nzb_key
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /api?mode=version
                    port: *port
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            resources:
              requests:
                cpu: 5m
                memory: 1Gi
              limits:
                memory: 12Gi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL

    service:
      app:
        controller: sabnzbd
        ports:
          http:
            port: *port

    route:
      app:
        hostnames:
          - sabnzbd.negative7.com
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: https
        rules:
          - backendRefs:
              - identifier: app
                port: *port

    persistence:
      config:
        existingClaim: sabnzbd
        advancedMounts:
          sabnzbd:
            app:
              - path: /config
      completed:
        enabled: true
        type: nfs
        server: freenas.homelab.internal
        path: /mnt/tank/data
        globalMounts:
          - path: /completed
      temp:
        type: emptyDir
        advancedMounts:
          sabnzbd:
            app:
              - path: /tmp
      ephemeral:
        type: custom
        volumeSpec:
          ephemeral:
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                storageClassName: "openebs-hostpath"
                resources:
                  requests:
                    storage: 100Gi
        advancedMounts:
          sabnzbd:
            app:
              - path: /incomplete
                subPath: incomplete
