---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: victoria-logs
spec:
  chartRef:
    kind: OCIRepository
    name: victoria-logs
  interval: 30m
  values:
    fullnameOverride: victoria-logs
    server:
      persistentVolume:
        enabled: true
        storageClassName: ceph-block
        size: 20Gi
      retentionPeriod: 14d
      route:
        enabled: true
        hostnames:
          - victoria-logs.negative7.com
        parentRefs:
          - name: envoy-internal
            namespace: network

      serviceMonitor:
        enabled: true
    dashboards:
      enabled: false
