---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: trek
spec:
  components:
    - ../../../../components/anubis
    - ../../../../components/kanidm-oidc
  dependsOn:
    - name: kanidm
      namespace: security
  interval: 1h
  path: "./kubernetes/apps/selfhosted/trek/app"
  postBuild:
    substitute:
      APP: trek
      APP_NAMESPACE: selfhosted
      ANUBIS_TARGET: http://trek.selfhosted.svc.cluster.local:3000
      OIDC_CALLBACK: /api/auth/oidc/callback
      OIDC_SCOPES: '["openid", "profile", "email", "groups"]'
      SUBDOMAIN: travel
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: selfhosted
