---
# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/refs/heads/main/schema/compose-spec.json
configs:
  poll-config.yml:
    content: |
      - run_once: true
        url: https://github.com/negative7/home-ops.git
secrets:
  webhook_secret:
    file: /mnt/tank/home/admin/.config/doco-cd/webhook_secret
services:
  app:
    configs:
      - source: poll-config.yml
        target: /poll-config.yml
    container_name: doco-cd
    environment:
      HTTP_PORT: 8080
      LOG_LEVEL: info
      POLL_CONFIG_FILE: /poll-config.yml
      WEBHOOK_SECRET_FILE: /run/secrets/webhook_secret
      DEPLOY_CONFIG_BASE_DIR: ./docker/truenas/
    healthcheck:
      test:
        - CMD
        - /doco-cd
        - healthcheck
      start_period: 15s
      interval: 30s
      timeout: 5s
      retries: 3
    image: ghcr.io/kimdre/doco-cd:0.76.0@sha256:ef0df49fca5ccaa4c4e01e13bf99d15609c093dd08f53f0c94dacac2a72ed4bd
    ports:
      - 8080:8080
    restart: unless-stopped
    secrets:
      - webhook_secret
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - data:/data
volumes:
  data: {}
