---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/gateway.envoyproxy.io/backend_v1alpha1.json
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: Backend
metadata:
  labels:
    app.kubernetes.io/instance: adguard
    app.kubernetes.io/name: adguard
  name: adguard
spec:
  appProtocols:
    - gateway.envoyproxy.io/ws
    - gateway.envoyproxy.io/wss
  endpoints:
    - ip:
        address: 10.0.5.3
        port: 80
