---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: plex
spec:
  chart:
    spec:
      chart: app-template
      version: 4.1.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s-labs
        namespace: flux-system
  interval: 30m
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
  values:
    controllers:
      plex:
        pod:
          securityContext:
            runAsUser: 2000
            runAsGroup: 2000
            fsGroup: 2000
            fsGroupChangePolicy: "OnRootMismatch"
            supplementalGroups:
              - 44
              - 109
              - 65542
              - 10000
              - 1000
              - 1001

        containers:
          app:
            image:
              repository: ghcr.io/home-operations/plex
              tag: 1.41.9.9961
            env:
              PLEX_ADVERTISE_URL: https://10.2.0.105:32400,https://plex.negative7.com:443
              PLEX_NO_AUTH_NETWORKS: 10.0.1.0/16
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /identity
                    port: 32400
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 10
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
            resources:
              requests:
                cpu: 100m
              limits:
                gpu.intel.com/i915: 1
                memory: 9248M

    service:
      app:
        controller: plex
        type: LoadBalancer
        annotations:
          io.cilium/lb-ipam-ips: 10.2.0.105
        ports:
          http:
            port: &port 32400

    route:
      app:
        hostnames:
          - plex.negative7.com
        parentRefs:
          - name: external
            namespace: kube-system
            sectionName: https
        rules:
          - backendRefs:
              - identifier: app
                port: *port

    persistence:
      config:
        existingClaim: plex
        advancedMounts:
          plex:
            app:
              - path: /config
      plex-cache:
        existingClaim: plex-cache
        advancedMounts:
          plex:
            app:
              - path: /config/Library/Application Support/Plex Media Server/Cache
      tmpfs:
        type: emptyDir
        advancedMounts:
          plex:
            app:
              - path: /config/Library/Application Support/Plex Media Server/Logs
                subPath: log
              - path: /transcode
                subPath: transcode
      nfs-tv-media:
        type: nfs
        server: "freenas.homelab.internal"
        path: /mnt/tank/media/tv
        advancedMounts:
          plex:
            app:
              - path: /media/tv
      nfs-movies-media:
        type: nfs
        server: "freenas.homelab.internal"
        path: /mnt/tank/media/movies
        advancedMounts:
          plex:
            app:
              - path: /media/movies
      nfs-backup:
        type: nfs
        server: "freenas.homelab.internal"
        path: /mnt/tank/backups/plex
        advancedMounts:
          plex:
            app:
              - path: /config/Backups
