---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  # Flux-Kustomizations
  - ./flux-operator/ks.yaml
components:
  - ../../components/namespace
replacements:
  - path: ../../components/replacements/ks.yaml
