# yamllint disable
apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: sops-age
stringData:
    age.agekey: |
        # created: 2022-05-18T13:36:37Z
        # public key: age1tlmg2hsr6nag9cq6ws3h5r7fpzw6ekdh35av69uzetrth46f9vpsa8hqz9
        AGE-SECRET-KEY-15J62429Y68H6K6JJRNADSSPNF9H4UV5YHLUU8NCQ9JCNE9ZXJS2S9PAJ6Y
