---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
<<<<<<< HEAD
apiVersion: external-secrets.io
=======
apiVersion: external-secrets.io/v1
>>>>>>> 53286c8 (fix(eso): Bump v1beta1 to v1)
kind: ExternalSecret
metadata:
  name: zigbee2mqtt
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: zigbee2mqtt-secret
    creationPolicy: Owner
  data:
    - secretKey: mqtt_user
      remoteRef:
        key: EMQX
        property: user_mqtt_username
    - secretKey: mqtt_password
      remoteRef:
        key: EMQX
        property: user_mqtt_password
    - secretKey: zigbee_pan_id
      remoteRef:
        key: zigbee2mqtt
        property: config_pan_id
    - secretKey: zigbee_ext_pan_id
      remoteRef:
        key: zigbee2mqtt
        property: config_ext_pan_id
    - secretKey: zigbee_network_key
      remoteRef:
        key: zigbee2mqtt
        property: config_network_key