---
originRequest:
  originServerName: ingress-ext.negative7.com

ingress:
  - hostname: negative7.com
    service: &svc https://cilium-gateway-external.kube-system.svc.cluster.local
  - hostname: "*.negative7.com"
    service: *svc
  - service: http_status:404
