---
originRequest:
  originServerName: ingress-ext.negative7.com

ingress:
  - hostname: negative7.com
    service: &svc https://envoy-network-external-b1d9befd.network.svc.cluster.local
  - hostname: "*.negative7.com"
    service: *svc
  - service: http_status:404
