---
originRequest:
  originServerName: ingress-ext.negative7.com

ingress:
  - hostname: negative7.com
    service: &svc https://envoy-external.cloudflared.svc.cluster.local:443
  - hostname: "*.negative7.com"
    service: *svc
  - service: http_status:404
