---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: actions-runner-system
resources:
  - ./actions-runner-controller/ks.yaml
components:
  - ../../components/namespace
  - ../../components/flux/alerts
patches:
  - patch: |
      - op: add
        path: /metadata/name
        value: actions-runner-system
    target:
      kind: Namespace