---
customization:
  extraKernelArgs:
    - initcall_blacklist=algif_aead_init
    - selinux=0
    - -selinux
  systemExtensions:
    officialExtensions:
      - siderolabs/drbd
      - siderolabs/i915
      - siderolabs/intel-ucode
