---
# yaml-language-server: $schema=https://raw.githubusercontent.com/budimanjojo/talhelper/master/pkg/config/schemas/talconfig.json
clusterName: &clusterName home-ops

endpoint: https://k8s.homelab.internal:6443

# renovate: depName=ghcr.io/siderolabs/installer datasource=docker
talosVersion: v1.10.4
# renovate: depName=ghcr.io/siderolabs/kubelet datasource=docker
kubernetesVersion: v1.33.2

additionalApiServerCertSans: &san
  - k8s.homelab.internal
  - "127.0.0.1" # KubePrism
  - &talosControlplaneVip 10.2.0.20
additionalMachineCertSans: *san

cniConfig:
  name: none

nodes:
  - hostname: kharkiv.homelab.internal
    ipAddress: 10.2.0.21
    controlPlane: true
    nodeLabels:
      intel.feature.node.kubernetes.io/gpu: "true"
    installDiskSelector:
      model: "CL1-3D256-Q11*"
    networkInterfaces:
      - interface: eno1
        dhcp: true
        vip:
          ip: *talosControlplaneVip

  - hostname: vinnytsia.homelab.internal
    ipAddress: 10.2.0.22
    controlPlane: true
    nodeLabels:
      intel.feature.node.kubernetes.io/gpu: "true"
    installDiskSelector:
      model: "KXG60ZNV256G*"
    networkInterfaces:
      - interface: eno1
        dhcp: true
        vip:
          ip: *talosControlplaneVip


  - hostname: dnipro.homelab.internal
    ipAddress: 10.2.0.23
    controlPlane: true
    nodeLabels:
      intel.feature.node.kubernetes.io/gpu: "true"
    installDiskSelector:
      model: "CT1000MX500SSD1"
    networkInterfaces:
      - interface: eno1
        dhcp: true
        vip:
          ip: *talosControlplaneVip

  - hostname: kyiv.homelab.internal
    ipAddress: 10.2.0.24
    controlPlane: true
    nodeLabels:
      intel.feature.node.kubernetes.io/gpu: "true"
    installDiskSelector:
      model: "CT1000MX500SSD1"
    networkInterfaces:
      - interface: eno1
        dhcp: true
        vip:
          ip: *talosControlplaneVip

controlPlane:
  nodeLabels:
    topology.kubernetes.io/region: *clusterName
    topology.kubernetes.io/zone: m

  schematic:
    customization:
      extraKernelArgs:
        - -init_on_alloc                      # Less security, faster puter
        - -init_on_free                       # Less security, faster puter
        - -selinux                            # Less security, faster puter
        - apparmor=0                          # Less security, faster puter
        - init_on_alloc=0                     # Less security, faster puter
        - init_on_free=0                      # Less security, faster puter
        - intel_iommu=on                      # PCI Passthrough
        - iommu=pt                            # PCI Passthrough
        - mitigations=off                     # Less security, faster puter
        - security=none                       # Less security, faster puter
        - talos.auditd.disabled=1             # Less security, faster puter
      systemExtensions:
        officialExtensions:
          - siderolabs/intel-ucode
          - siderolabs/i915

  patches:
    # Configure containerd
    - |-
      machine:
        files:
          - op: create
            path: /etc/cri/conf.d/20-customization.part
            content: |
              [plugins]
                [plugins."io.containerd.grpc.v1.cri"]
                  enable_unprivileged_ports = true
                  enable_unprivileged_icmp = true
              [plugins."io.containerd.grpc.v1.cri".containerd]
                discard_unpacked_layers = false
              [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc]
                discard_unpacked_layers = false


    # Disable search domain everywhere
    - |-
      machine:
        network:
          disableSearchDomain: true

    # Enable host dns
    - |-
      machine:
        features:
          hostDNS:
            enabled: true
            resolveMemberNames: true
            forwardKubeDNSToHost: false

    # Mount openebs-hostpath in kubelet
    - |-
      machine:
          kubelet:
            extraMounts:
              - destination: /var/local/openebs
                type: bind
                source: /var/local/openebs
                options:
                  - rbind
                  - rshared
                  - rw

    # Configure kubelet
    - |-
      machine:
        kubelet:
          extraConfig:
            maxPods: 150
          nodeIP:
            validSubnets:
                - 10.2.0.0/24

    # Enable MutatingAdmissionPolicy
    - |-
      cluster:
        apiServer:
          extraArgs:
            runtime-config: admissionregistration.k8s.io/v1alpha1=true
            feature-gates: MutatingAdmissionPolicy=true

    # Configure cluster
    - |-
      cluster:
        allowSchedulingOnControlPlanes: true
        coreDNS:
            disabled: true
        proxy:
          disabled: true
        scheduler:
          config:
            apiVersion: kubescheduler.config.k8s.io/v1
            kind: KubeSchedulerConfiguration
            profiles:
              - schedulerName: default-scheduler
                pluginConfig:
                  - name: PodTopologySpread
                    args:
                      defaultingType: List
                      defaultConstraints:
                        - maxSkew: 1
                          topologyKey: kubernetes.io/hostname
                          whenUnsatisfiable: ScheduleAnyway

    # Configure etcd
    - |-
      cluster:
        etcd:
          advertisedSubnets:
            - 10.2.0.0/24

    # Configure NFS mount options
    - |
      machine:
        files:
          - op: overwrite
            path: /etc/nfsmount.conf
            permissions: 0o644
            content: |
              [ NFSMount_Global_Options ]
              nfsvers=4.2
              hard=True
              noatime=True
              nconnect=16

    # Configure static host entries
    - |-
      machine:
        network:
          extraHostEntries:
            - ip: 10.2.0.20
              aliases:
                - k8s.homelab.internal

    # Configure custom sysctls
    - |-
      machine:
        sysctls:
          fs.inotify.max_user_instances: 8192    # Watchdog
          fs.inotify.max_user_watches: 1048576   # Watchdog
          user.max_user_namespaces: 11255        # User namespaces
          net.core.rmem_max: 67108864            # Cloudflared / QUIC
          net.core.wmem_max: 67108864            # Cloudflared / QUIC

    # Configure udev rules
    - |-
      machine:
        udev:
          rules:
            # Intel GPU
            - SUBSYSTEM=="drm", KERNEL=="renderD*", GROUP="44", MODE="0660"

    # Disable default API server admission plugins.
    - |-
      - op: remove
        path: /cluster/apiServer/admissionControl

    # Enable K8s Talos API Access
    - |-
      machine:
        features:
          kubernetesTalosAPIAccess:
            enabled: true
            allowedRoles:
              - os:admin
            allowedKubernetesNamespaces:
              - actions-runner-system
              - system-upgrade
