---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: scrape
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: scrape-secret
    creationPolicy: Owner
  data:
    - secretKey: hass_token
      remoteRef:
        key: home-assistant
        property: HASS_PROM_TOKEN
