---
apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
data:
  bookmarks.yaml: |
    ---
  docker.yaml: |
    ---
  kubernetes.yaml: |
    ---
    mode: cluster

  services.yaml: |
    ---


  settings.yaml: |
    ---
    title: My Personal Home Dashboard
    theme: dark
    color: slate
    headerStyle: clean
    target: _blank
    layout:
      Media:
        style: row
        columns: 4
      Network:
        style: row
      Favorites:
        style: row
        columns: 3
    quicklaunch:
      searchDescription: true
      hideInternetSearch: true
      hideVisitURL: true

  widgets.yaml: |
    ---
