---
apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
data:
  bookmarks.yaml: |
    ---
  docker.yaml: |
    ---
  kubernetes.yaml: |
    ---
    mode: cluster

  services.yaml: |
    ---
    - Media:
        - Plex:
            icon: plex.png
            href: https://plex.negative7.com
            description: Plex Server
            widget:
              type: plex
              url: http://plex.negative7.com
              token: {{HOMEPAGE_VAR_PLEX_TOKEN}}
        - Jellyfin:
            icon: jellyfin.png
            href: https://jellyfin.negative7.com
            description: Jellyfin Server
            widget:
              type: jellyfin
              url: http://jellyfin.media.svc.cluster.local:8096
              key: {{HOMEPAGE_VAR_JELLYFIN_KEY}}
              enableNowPlaying: true
        - Requests:
            icon: overseerr.png
            href: https://requests.negative7.com
            description: Media Requests
            widget:
              type: overseerr
              url: http://overseerr.media.svc.cluster.local:80
              key: {{HOMEPAGE_VAR_OVERSERR_KEY}}
        - Radarr:
            icon: radarr.png
            href: https://radarr.negative7.com
            description: Movies Management
            widget:
              type: radarr
              url: http://radarr.downloads.svc.cluster.local:7878
              key: {{HOMEPAGE_VAR_RADARR_KEY}}
        - Sonarr:
            icon: sonarr.png
            href: https://sonarr.negative7.com
            description: TV Shows Management
            widget:
              type: sonarr
              url: http://sonarr.downloads.svc.cluster.local:8989
              key: {{HOMEPAGE_VAR_SONARR_KEY}}
    - Network:
        - AdGuardHome:
            icon: adguard-home.png
            href: https://adguard.negative7.com
            description: Ad Blocking DNS
            widget:
              type: adguard
              url: https://adguard.negative7.com
              username: {{HOMEPAGE_VAR_AGH_USERNAME}}
              password: {{HOMEPAGE_VAR_AGH_PASSWORD}}
    - Favorites:
        - My GitHub Repo:
            icon: si-github
            href: https://github.com/negative7
            description: My Code Repository
        - Grafana Dashboard:
            icon: si-grafana
            href: https://grafana.negative7.com
            description: My Cluster Metrics Visualization
        - k8s-at-home-search:
            icon: si-kubernetes
            href: https://nanne.dev/k8s-at-home-search/
            description: Search KAH HelmReleases

  settings.yaml: |
    ---
    title: My Personal Home Dashboard
    theme: dark
    color: slate
    headerStyle: clean
    target: _blank
    layout:
      Media:
        style: row
        columns: 4
      Network:
        style: row
      Favorites:
        style: row
        columns: 3
    quicklaunch:
      searchDescription: true
      hideInternetSearch: true
      hideVisitURL: true

  widgets.yaml: |
    ---
    - search:
        provider:
          - google
          - duckduckgo
    - openmeteo:
        label: Home
        latitude: {{HOMEPAGE_VAR_HOME_LATITUDE}}
        longitude: {{HOMEPAGE_VAR_HOME_LONGITUDE}}
        units: metric
        cache: 5
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: home-cluster
        nodes:
          show: false
