---
apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
data:
  bookmarks.yaml: |
    ---
  docker.yaml: |
    ---
  kubernetes.yaml: |
    ---
  services.yaml: |
    ---
  settings.yaml: |
    ---
  widgets.yaml: |
    ---
