---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: homepage
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: homepage-secret
    creationPolicy: Owner
    template:
      data:
        HOMEPAGE_VAR_HOME_LATITUDE: "{{ .homepage_home_latitude }}"
        HOMEPAGE_VAR_HOME_LONGITUDE: "{{ .homepage_home_longitude }}"
        HOMEPAGE_VAR_JELLYFIN_KEY: "{{ .homepage_jellyfin_key }}"
        HOMEPAGE_VAR_OVERSERR_KEY: "{{ .homepage_overseerr_key }}"
        HOMEPAGE_VAR_RADARR_KEY: "{{ .homepage_radarr_key }}"
        HOMEPAGE_VAR_SONARR_KEY: "{{ .homepage_sonarr_key }}"
        HOMEPAGE_VAR_HASS_TOKEN: "{{ .homepage_hass_token }}"
        HOMEPAGE_VAR_PLEX_TOKEN: "{{ .homepage_plex_token }}"
        HOMEPAGE_VAR_AGH_USERNAME: "{{ .homepage_agh_username }}"
        HOMEPAGE_VAR_AGH_PASSWORD: "{{ .homepage_agh_password }}"
        HOMEPAGE_VAR_TAUTULLI: "{{ .homepage_tautulli }}"

  dataFrom:
    - extract:
        key: homepage
      rewrite:
        - regexp:
            source: "(.*)"
            target: "homepage_$1"
