---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: homepage
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: homepage-secret
    creationPolicy: Owner
    template:
      data:
        HOMEPAGE_VAR_HOME_LATITUDE: "{{ .homepage_var_home_latitude }}"
        HOMEPAGE_VAR_HOME_LONGITUDE: "{{ .homepage_var_home_longitude }}"
        HOMEPAGE_VAR_JELLYFIN_KEY: "{{ .homepage_var_jellyfin_key }}"
        HOMEPAGE_VAR_OVERSERR_KEY: "{{ .homepage_var_overseerr_key }}"
        HOMEPAGE_VAR_RADARR_KEY: "{{ .homepage_var_radarr_key }}"
        HOMEPAGE_VAR_SONARR_KEY: "{{ .homepage_var_sonarr_key }}"
        HOMEPAGE_VAR_HASS_TOKEN: "{{ .homepage_var_hass_token }}"

  dataFrom:
    - extract:
        key: homepage
      rewrite:
        - regexp:
            source: "(.*)"
            target: "homepage_var_$1"
