---
apiVersion: v1
kind: Service
metadata:
  name: &app adguard
  namespace: network
  labels:
    app.kubernetes.io/name: *app
    app.kubernetes.io/instance: *app
spec:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app.kubernetes.io/name: *app

---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: &app adguard
  namespace: network
  labels:
    app.kubernetes.io/name: *app
    app.kubernetes.io/instance: *app
spec:
  hostnames:
    - adguard.negative7.com
  parentRefs:
    - name: internal
      namespace: network
      sectionName: https
  rules:
    - backendRefs:
        - name: *app
          namespace: network
          port: 80
      matches:
        - path:
            type: PathPrefix
            value: /

---
apiVersion: v1
kind: Endpoints
metadata:
  name: adguardhome
subsets:
  - addresses:
      - 10.0.5.3
    ports:
      - name: http
        port: 3000
        protocol: TCP
