---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/gateway.envoyproxy.io/backend_v1alpha1.json
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: Backend
metadata:
  labels:
    app.kubernetes.io/instance: adguard
    app.kubernetes.io/name: adguard
  name: adguard
spec:
  appProtocols:
    - gateway.envoyproxy.io/ws
    - gateway.envoyproxy.io/wss
  endpoints:
    - ip:
        address: 10.0.5.3
        port: 80
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: adguard
spec:
  hostnames:
    - adguard.negative7.com
  parentRefs:
    - name: envoy-internal
      namespace: network
  rules:
    - backendRefs:
        - group: gateway.envoyproxy.io
          kind: Backend
          name: adguard
      matches:
        - path:
            type: PathPrefix
            value: /
