---
apiVersion: v1
kind: Service
metadata:
  name: &app doco-cd-proxy
  namespace: network
  labels:
    app.kubernetes.io/name: *app
    app.kubernetes.io/instance: *app
spec:
  type: ClusterIP
  ports:
    - name: https
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app.kubernetes.io/name: *app

---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: &app doco-cd-proxy
  namespace: network
  labels:
    app.kubernetes.io/name: *app
    app.kubernetes.io/instance: *app
spec:
  hostnames:
    - doco.negative7.com
  parentRefs:
    - name: envoy-external
      namespace: network
      sectionName: https
  rules:
    - backendRefs:
        - name: *app
          namespace: network
          port: 8080
      matches:
        - path:
            type: PathPrefix
            value: /

---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: &app doco-cd-proxy
  namespace: network
  labels:
    app.kubernetes.io/name: *app
    kubernetes.io/service-name: *app
addressType: IPv4
ports:
  - name: https
    port: 8080
    protocol: TCP
endpoints:
  - addresses:
      - 10.0.1.10
    conditions:
      ready: true
