---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: trek
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: trek-secret
    creationPolicy: Owner
    template:
      data:
        ADMIN_EMAIL: "{{ .trek_ADMIN_EMAIL }}"
        ADMIN_PASSWORD: "{{ .trek_ADMIN_PASSWORD }}"
        ENCRYPTION_KEY: "{{ .trek_ENCRYPTION_KEY }}"
  dataFrom:
    - extract:
        key: trek
      rewrite:
        - regexp:
            source: "(.*)"
            target: "trek_$1"
