---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/postgresql.cnpg.io/cluster_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
spec:
  description: Shared PostgreSQL cluster
  imageName: ghcr.io/cloudnative-pg/postgresql:18.4-standard-trixie
  instances: 2
  storage:
    size: 20Gi
    storageClass: miroir-local
  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      memory: 1Gi
  certificates:
    serverTLSSecret: postgres-server-cert
    serverCASecret: postgres-server-cert
    clientCASecret: postgres-client-ca
    replicationTLSSecret: postgres-replication-cert
  postgresql:
    pg_hba:
      - hostssl all all all cert clientcert=verify-full map=pooler-map
      - host all all all scram-sha-256
    pg_ident:
      - pooler-map pooler-rw all
    parameters:
      max_connections: "200"
      shared_buffers: 256MB
      max_locks_per_transaction: "128"
      timescaledb.telemetry_level: "off"
    shared_preload_libraries:
      - vchord.so
      - timescaledb
    extensions:
      - name: vchord
        image:
          reference: ghcr.io/tensorchord/vchord-scratch:pg18-v1.1.1@sha256:bdea43bed2a414e21bbf71767bf6f0739747ac480b267b51772dc214ac28dcb3
        dynamic_library_path:
          - /usr/lib/postgresql/18/lib
        extension_control_path:
          - /usr/share/postgresql/18/
      - name: postgis
        image:
          reference: ghcr.io/cloudnative-pg/postgis-extension:3.6.4-18-trixie@sha256:4bdfebf86a7d4e9b186efd74b24ee60798007ffda0f10a5c919eb3ef120e1521
        ld_library_path:
          - system
      - name: timescaledb-oss
        image:
          reference: ghcr.io/cloudnative-pg/timescaledb-oss:2.29.0-18-trixie@sha256:a00c22ee1fa7cd45635b892b7c053fec1c33411e63a683fbb995cc79bfeb6709
  plugins:
    - name: barman-cloud.cloudnative-pg.io
      enabled: true
      isWALArchiver: true
      parameters:
        barmanObjectName: postgres-backup
  monitoring:
    enablePodMonitor: true
  bootstrap:
    initdb:
      database: app
      owner: app
      encoding: UTF8
