---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/postgresql.cnpg.io/cluster_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
  annotations:
    cnpg.io/skipEmptyWalArchiveCheck: enabled
spec:
  instances: 2

  imageName: ghcr.io/cloudnative-pg/postgresql:18.4-standard-trixie@sha256:f0cc49632b5cc1e51f65ba03658c89bd31d64ea2672b14843a808a8d281417e1

  storage:
    size: 8Gi
    storageClass: miroir-local

  bootstrap:
    recovery:
      source: &src source

  plugins:
    - name: &plugin barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: &store postgres-backup
  externalClusters:
    - name: *src
      plugin:
        name: *plugin
        parameters:
          barmanObjectName: *store
          serverName: postgres

  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      memory: 1Gi

  certificates:
    serverTLSSecret: postgres-server-cert
    serverCASecret: postgres-server-cert
    clientCASecret: postgres-client-ca
    replicationTLSSecret: postgres-replication-cert

  postgresql:
    pg_hba:
      - hostssl all all all cert clientcert=verify-full map=pooler-map
      - host all all all scram-sha-256
    pg_ident:
      - pooler-map pooler-rw all
    shared_preload_libraries:
      - "vchord"
      - "timescaledb"
    parameters:
      timescaledb.telemetry_level: "off"
      max_locks_per_transaction: "128"

    extensions:
      - name: pgvector
        image:
          reference: ghcr.io/cloudnative-pg/pgvector:0.8.6-18-trixie@sha256:c3fe71d306fe3dfad4e71b2585c58034c2da5f234a18cd4b964ed03e1dc858a9
      - name: vchord
        image:
          reference: ghcr.io/tensorchord/vchord-scratch:pg18-v1.1.1@sha256:bdea43bed2a414e21bbf71767bf6f0739747ac480b267b51772dc214ac28dcb3
        dynamic_library_path:
          - /usr/lib/postgresql/18/lib
        extension_control_path:
          - /usr/share/postgresql/18/
      - name: postgis
        image:
          reference: ghcr.io/cloudnative-pg/postgis-extension:3.6.4-18-trixie@sha256:fa68eaa7fef85dc1d64193f27cf373ed6c246b6b7579c82660ee907773559f0f
        ld_library_path:
          - system
      - name: timescaledb-oss
        image:
          reference: ghcr.io/cloudnative-pg/timescaledb-oss:2.29.1-18-trixie@sha256:c82221f583d33795d022d4f9c5e0283bd93991d30e63f35874e52179795aa26d

  monitoring:
    enablePodMonitor: true
