---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sure
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: sure-secret
    creationPolicy: Owner
    template:
      data:
        SECRET_KEY_BASE: "{{ .sure_secret_key_base }}"
        ACTIVE_RECORD_ENCRYPTION_PRIMARY_KEY: "{{ .sure_ar_encryption_primary_key }}"
        ACTIVE_RECORD_ENCRYPTION_DETERMINISTIC_KEY: "{{ .sure_ar_encryption_deterministic_key }}"
        ACTIVE_RECORD_ENCRYPTION_KEY_DERIVATION_SALT: "{{ .sure_ar_encryption_key_derivation_salt }}"
  dataFrom:
    - extract:
        key: sure
      rewrite:
        - regexp:
            source: "(.*)"
            target: "sure_$1"
