---
apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: sure-postgresql-backup
spec:
  configuration:
    destinationPath: s3://cnpg-backups/sure
    endpointURL: http://lviv.homelab.internal:9000
    s3Credentials:
      accessKeyId:
        name: sure-garage-secret
        key: ACCESS_KEY_ID
      secretAccessKey:
        name: sure-garage-secret
        key: SECRET_ACCESS_KEY
      region:
        name: sure-garage-secret
        key: REGION
    wal:
      compression: zstd
      maxParallel: 2
    data:
      compression: gzip
      jobs: 2
  retentionPolicy: 14d
