---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: victoria-logs
spec:
  chartRef:
    kind: OCIRepository
    name: victoria-logs
  interval: 30m
  values:
    fullnameOverride: victoria-logs
    retentionPeriod: 14d
    server:
      persistentVolume:
        enabled: true
        storageClassName: ceph-block
        size: 20Gi
      serviceMonitor:
        enabled: true
    dashboards:
      enabled: true
      annotations:
        grafana_folder: observability
      labels:
        grafana_dashboard: "1"
