---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: system-controllers
resources:
  - ./k8tz/ks.yaml
  - ./snapshot-controller/ks.yaml
components:
  - ../../components/namespace
replacements:
  - path: ../../components/replacements/ks.yaml
