---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname esphome
  namespace: flux-system
spec:
  targetNamespace: home
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname
  interval: 10m
  path: ./kubernetes/apps/home/esphome/app
  prune: false # revert to true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: false
  dependsOn:
    - name: rook-ceph-cluster
    - name: volsync
    - name: onepassword-store
      namespace: external-secrets
  postBuild:
    substitute:
      APP: *appname
      APP_UID: "0"
      APP_GID: "0"
      VOLSYNC_CAPACITY: 5Gi
