---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mealie
spec:
  chartRef:
    kind: OCIRepository
    name: mealie
  interval: 30m
  values:
    controllers:
      mealie:
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          securityContext:
            fsGroup: 1000
            fsGroupChangePolicy: OnRootMismatch
            runAsGroup: 1000
            runAsNonRoot: true
            runAsUser: 1000
        containers:
          app:
            image:
              repository: ghcr.io/mealie-recipes/mealie
              tag: v3.22.0
            env:
              TZ: America/New_York
              ALLOW_SIGNUP: false
              BASE_URL: https://mealie.negative7.com
              SMTP_HOST: smtp-relay.system.svc.cluster.local
              SMTP_PORT: 25
              SMTP_FROM_NAME: Mealie
              SMTP_FROM_EMAIL: noreply@negative7.com
              SMTP_AUTH_STRATEGY: NONE
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /api/app/about
                    port: &httpPort 9000
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 5
                  failureThreshold: 3
              readiness: *probes
              startup:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /api/app/about
                    port: *httpPort
                  periodSeconds: 5
                  timeoutSeconds: 5
                  failureThreshold: 30
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 1Gi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
    persistence:
      data:
        existingClaim: mealie
        globalMounts:
          - path: /app/data
      tmpfs:
        type: emptyDir
        globalMounts:
          - path: /tmp
    route:
      app:
        hostnames:
          - mealie.negative7.com
        parentRefs:
          - name: envoy-internal
            namespace: network
    service:
      app:
        ports:
          http:
            port: *httpPort
