---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: open-webui
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: open-webui-secret
    creationPolicy: Owner
    template:
      data:
        OAUTH_CLIENT_ID: "{{ .openwebui_oidc_client_id }}"
        OAUTH_CLIENT_SECRET: "{{ .openwebui_oidc_client_secret }}"
        WEBUI_SECRET_KEY: "{{ .openwebui_secret_key }}"
        MEMINI_API_KEY: "{{ .memini_api_key }}"
        OPENAI_API_KEY: "{{ .litellm_master_key }}"
  dataFrom:
    - extract:
        key: open-webui
      rewrite:
        - regexp:
            source: "(.*)"
            target: "openwebui_$1"
    - extract:
        key: memini
      rewrite:
        - regexp:
            source: "(.*)"
            target: "memini_$1"
    - extract:
        key: litellm
      rewrite:
        - regexp:
            source: "(.*)"
            target: "litellm_$1"
