---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: network
resources:
  - ./cloudflared/ks.yaml
  - ./echo-server/ks.yaml
  - ./envoy-gateway/ks.yaml
  - ./external-dns/ks.yaml
  - ./external-services/ks.yaml
  - ./multus/ks.yaml
  # - ./openspeedtest/ks.yaml
components:
  - ../../components/namespace
  - ../../components/flux/alerts
patches:
  - patch: |
      - op: add
        path: /metadata/name
        value: network
    target:
      kind: Namespace
